---
title: "Modelling with individual patient data"
author: "Mi Jun Keng, Iryna Schlackow, Eleanor Pullenayegum"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
bibliography: references.bib
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


## Introduction 


```{r}

## Load required packages
library(tidyverse)

## Specify file location 
wd <- getwd()
dir_data <- file.path(wd, "data")

## Read in dataset 
df <- read.csv(file.path(dir_data, "10TT_synth_280921.csv")) %>% 
  mutate(across(c("arm", "sex", "bmicat"), as.factor))
```


### Dataset description 

For illustration, we will be using a synthetic dataset generated based on the Ten Top Tips trial [@beeken_brief_2017].


### Resource use and costs

### Utilities & QALYs

### Analysis dataset


```{r child = 'frequentist.Rmd'}
```


```{r child = 'bayesian.Rmd'}
```


## References 

<div id="refs"></div>
